[workspace]
resolver = "2"
members = ["copy-includes", "desktop", "renderer-core", "wasm"]

[workspace.dependencies]
wgpu = { version = "0.20.0", default-features = false, features = [
  "webgpu",
  "wgsl",
  "naga",
] }
winit = { version = "0.30.0" }
tracing = { version = "0.1.40" }
thiserror = "1.0.60"
glam = { version = "0.27", features = ["bytemuck"] }
glamour = "0.11.1"
encase = { version = "0.8", features = ["glam"] }
bytemuck = { version = "1.16.0", features = ["derive"] }
nanoserde = "0.1.37"

