[workspace]
resolver = "2"
members = ["copy-includes", "desktop", "renderer-core", "wasm"]

[workspace.dependencies]
wgpu = { version = "22.1.0", default-features = false, features = [
  "webgpu",
  "wgsl",
] }
winit = { version = "0.30.4" }
tracing = { version = "0.1.40" }
thiserror = "1.0.63"
glam = { version = "0.28", features = ["bytemuck"] }
encase = { version = "0.9.0", features = ["glam"] }
bytemuck = { version = "1.16.3", features = ["derive"] }
nanoserde = "0.1.37"
