[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
default-run = "desktop"

[dependencies]
anyhow = "1.0.83"
glam = { workspace = true }
glamour = { workspace = true }
nanoserde = { workspace = true }
pollster = "0.3"
renderer-core = { path = "../renderer-core" }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18" }
wgpu = { workspace = true }
wgpu-profiler = "0.17.0"
winit = { workspace = true }
winit_input_helper = { workspace = true }

[dev-dependencies]
criterion = "0.3"
