[package]
name = "desktop"
version = "0.2.0"
edition = "2021"
default-run = "desktop"

[dependencies]
anyhow = "1.0"
glam = { workspace = true }
nanoserde = { workspace = true }
pollster = "0.3"
renderer-core = { path = "../renderer-core" }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18", default-features = false, features = [
  "smallvec",
  "fmt",
  "std",
] }
wgpu = { workspace = true }
wgpu-profiler = "0.18.2"
winit = { workspace = true }

[features]
default = []
tracy = ["renderer-core/tracy"]
