[package]
name = "renderer-core"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[lib]
bench = false

[dependencies]
anyhow = "1.0"
bytemuck = { workspace = true }
encase = { workspace = true }
glam = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
web-time = "1.1.0"
wgpu = { workspace = true }
wgpu-profiler = "0.18.1"
# wgsl-parser = "0.5.0"
winit = { workspace = true }
bevy_ecs = { workspace = true }

[dev-dependencies]
criterion = "0.5.1"
pollster = "0.3"

[[bench]]
name = "gpu_bench"
harness = false

[build-dependencies]
wgsl_to_wgpu = "0.10.1"

[features]
tracy = ["wgpu-profiler/tracy"]
