[package]
name = "renderer-core"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[lib]
bench = false

[dependencies]
# wgsl-parser = "0.5.0"
anyhow = "1.0"
any_spawner = { version = "0.1.1" }
bytemuck = { workspace = true }
comemo = { workspace = true }
encase = { workspace = true }
glam = { workspace = true }
indexmap = { workspace = true }
pinky-swear = "6.2.0"
reactive_graph = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
web-time = "1.1.0"
web-sys = { version = "0.3.70", optional = true, features = [
    "HtmlCanvasElement",
] }
wgpu = { workspace = true }
wgpu-profiler = "0.18.2"
winit = { workspace = true }

[dev-dependencies]
criterion = "0.5.1"
pollster = "0.3"

[[bench]]
name = "gpu_bench"
harness = false

[build-dependencies]
wgsl_to_wgpu = "0.10.1"

[features]
default = []
tracy = ["wgpu-profiler/tracy"]
wasm-bindgen = ["web-sys"]
