[package]
build = "build.rs"
edition = "2021"
name = "renderer-core"
version = "0.2.0"

[lib]
bench = false

[dependencies]
# wgsl-parser = "0.5.0"
any_spawner = { version = "0.1.1" }
anyhow = "1.0"
bytemuck = { workspace = true }
encase = { workspace = true }
glam = { workspace = true }
indexmap = { workspace = true }
notify-debouncer-full = { version = "0.4.0", optional = true }
pinky-swear = "6.2.0"
reactive_graph = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
web-sys = { version = "0.3.72", optional = true, features = [
    "HtmlCanvasElement",
] }
web-time = "1.1.0"
wgpu = { workspace = true }
wgpu-profiler = "0.18.2"
winit = { workspace = true }

[dev-dependencies]
any_spawner = { version = "0.1.1", features = ["futures-executor"] }
criterion2 = "0.5.1"
pollster = "0.3"

[[bench]]
harness = false
name = "gpu_bench"

[build-dependencies]
wgsl_to_wgpu = { version = "0.10.1", git = "https://github.com/stefnotch/wgsl_to_wgpu.git", branch = "feat/backport-shader-source" }

[features]
default = []
desktop = ["notify-debouncer-full"]
tracy = ["wgpu-profiler/tracy"]
wasm-bindgen = ["web-sys"]
