[package]
name = "renderer-core"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.86"
bytemuck = { workspace = true }
encase = { workspace = true }
glam = { workspace = true }
glamour = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
web-time = "1.1.0"
wgpu = { workspace = true }
wgpu-profiler = "0.17.0"
# wgsl-parser = "0.5.0"
winit = { workspace = true }
slotmap = "1.0.7"

[build-dependencies]
wgsl_to_wgpu = "0.8.0"

[features]
tracy = ["wgpu-profiler/tracy"]
