[package]
name = "renderer-core"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.83"
bytemuck = { workspace = true }
encase = { workspace = true }
glam = { workspace = true }
glamour = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
winit_input_helper = { workspace = true }

[dev-dependencies]
criterion = "0.3"
pollster = "0.3"

[[bench]]
name = "gpu_bench"
harness = false

[build-dependencies]
wgsl_to_wgpu = "0.8.0"
