[package]
name = "web"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
console_error_panic_hook = "0.1.7"
glam = { workspace = true }
renderer-core = { path = "../renderer-core" }
time = { version = "0.3.36", features = ["wasm-bindgen"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18", default-features = false, features = [
  "smallvec",
  "fmt",
  "std",
  "time",
  "json",
] }
tracing-web = "0.1.3"
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
serde = { version = "1.0.209", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
web-sys = { version = "0.3.70", features = ["HtmlCanvasElement"] }
wgpu = { workspace = true }
winit = { workspace = true }
