name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run copy-includes
      run: cargo run --bin copy-includes
      working-directory: ./parametric-renderer-core
    - name: Build 
      run: cargo build --verbose
      working-directory: ./parametric-renderer-core
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Deploy over SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SCP_HOST }}
        username: ${{ secrets.SCP_USER }}
        password: ${{ secrets.SCP_PASSWORD }}
        source: "dist"
        target: "/home/math2model/htdocs"
        rm: true
